[package]
name = "grid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.21.3"
webpki-roots = "0.24.0"
mio ={version="0.8.8", features=["net", "os-poll"]}
rcgen = "0.11.1"